#!/bin/sh

echo "🔄 Generazione documentazione in corso..."

# Esegue lo script di documentazione
bash make-docs.sh

# Aggiunge i file aggiornati allo staging del commit corrente
git add docs README.md

echo "✅ Documentazione aggiornata e aggiunta al commit!"
