= Appunti di Analisi Matematica
Emanuele Paolini
:stem: latexmath
:toc:

[latexmath]
++++        
\newcommand{\eps}{\varepsilon}
\newcommand{\ENCLOSE}[1]{\left\{#1\right\}}
\newcommand{\Enclose}[1]{\left[#1\right]}
\newcommand{\enclose}[1]{\left(#1\right)}
\newcommand{\abs}[1]{\left\vert#1\right\vert}
\newcommand{\Abs}[1]{\left\Vert#1\right\Vert}
\newcommand{\closeinterval}[1]{\left[#1\right]}
\newcommand{\openinterval}[1]{\left(#1\right)}
\newcommand{\closeopeninterval}[1]{\left[#1\right)}
\newcommand{\opencloseinterval}[1]{\left(#1\right]}
\renewcommand{\B}{\mathcal B}   
\renewcommand{\P}{\mathcal P}   
\newcommand{\F}{\mathcal F}
\newcommand{\NN}{\mathbb N}   
\newcommand{\ZZ}{\mathbb Z}   
\newcommand{\QQ}{\mathbb Q}   
\newcommand{\RR}{\mathbb R}
\newcommand{\CC}{\mathbb C}   
\newcommand{\KK}{\mathbb K}   
\newcommand{\sgn}{\mathrm{sgn}}
\newcommand{\tg}{\mathrm{tg}}
\newcommand{\arctg}{\mathrm{arctg}}
\newcommand{\tgh}{\mathrm{tgh}}
\newcommand{\settsinh}{\mathrm{settsinh}}
\newcommand{\settcosh}{\mathrm{settcosh}}
\newcommand{\setttgh}{\mathrm{setttgh}}
\newcommand{\MoveEqLeft}[1]{#1}
++++

include::chap-00-introduzione.adoc[]

include::chap-01-reali.adoc[]

include::chap-02-successioni.adoc[]

include::chap-03-serie.adoc[]

include::chap-04-complessi.adoc[]

include::chap-05-derivate.adoc[]

include::chap-06-integrali.adoc[]

include::chap-07-spazi.adoc[]

include::chap-08-ricorrenza.adoc[]

include::chap-09-edo.adoc[]

include::chap-98-algebra.adoc[]

include::chap-99-appendix.adoc[]
