name: compile and release
on:
  push:
    tags:
      - '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]'    # Tag IT: es. 2026-10-28
      - '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]-en' # Tag EN: es. 2026-10-28-en

jobs:
  Release-IT:
    runs-on: ubuntu-latest
    if: "!endsWith(github.ref, '-en')"
    steps:
      - uses: actions/checkout@v4
      - uses: xu-cheng/latex-action@v2
        with:
          root_file: AnalisiUno.tex
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "AnalisiUno.pdf"
          artifactContentType: "application/pdf"
          body: "${{ github.event.head_commit.message }}"
          token: ${{ secrets.GITHUB_TOKEN }}

  Release-EN:
    runs-on: ubuntu-latest
    if: endsWith(github.ref, '-en')
    steps:
      - uses: actions/checkout@v4
      - uses: xu-cheng/latex-action@v2
        with:
          root_file: AnalisiUnoEn.tex
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "AnalisiUnoEn.pdf"
          artifactContentType: "application/pdf"
          body: "${{ github.event.head_commit.message }}"
          token: ${{ secrets.GITHUB_TOKEN }}