name: compile, build, commit and release
on: [push]
jobs:
  Compile-LaTeX:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: compile LaTeX project
        uses: xu-cheng/latex-action@v2
        with:
          root_file: AnalisiUno.tex
      - name: upload PDF artifact
        uses: actions/upload-artifact@v2
        with:
          name: AnalisiUno.pdf
          path: AnalisiUno.pdf
      - name: upload myaux artifact
        uses: actions/upload-artifact@v2
        with:
          name: AnalisiUno.myaux
          path: AnalisiUno.myaux
  Build-Docs:
    runs-on: ubuntu-latest
    needs: Compile-LaTeX
    if: startsWith(github.ref, 'refs/heads/')
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: download myaux artifact
        uses: actions/download-artifact@v2
        with:
          name: AnalisiUno.myaux
      - name: make-docs
        run: bash make-docs.sh
      - name: commit doc changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: automated push
          message: 'automatic creation of docs'
          add: '["docs", "README.md"]'
      - run: echo "🍏 This job's status is ${{ job.status }}."
